// ============================================================
// LeadForge AI — Template UI Translations
// ============================================================

export const UI = {
  fr: {
    lang: 'fr', hreflang: 'fr',
    navAbout: 'À propos', navServices: 'Services', navWhy: 'Pourquoi nous', navAvis: 'Avis', navContact: 'Contact',
    heroCall: 'Appeler Maintenant', heroHours: 'Horaires & Urgences', heroNote: 'Réponse rapide · Sans engagement',
    monLunVen: 'Lun – Ven', monSam: 'Samedi', monDim: 'Dimanche', monDimUrg: 'Urgences uniquement',
    trustDefault: 'Professionnel certifié',
    svcLabel: 'Ce que nous proposons', svcTitle: 'Nos Services', svcDesc: 'Des prestations pensées pour répondre à vos besoins avec soin et expertise.', svcLink: 'En savoir plus',
    aboutLabel: 'À propos de nous', aboutTitle: 'Notre Établissement', aboutBadge: 'Ans d\'expérience',
    whyLabel: 'Pourquoi nous choisir ?', whySatisfaction: 'Satisfaction', whyExp: 'Ans d\'Expérience',
    statsAvis: 'Avis Clients', statsExp: 'Ans d\'Expérience', statsNote: 'Note Google', statsSat: 'Satisfaction',
    procLabel: 'Comment ça marche', procTitle: 'Un Accompagnement Sur Mesure', procDesc: 'Du premier contact à la réalisation, nous vous accompagnons à chaque étape.',
    galleryLabel: 'Découvrir', galleryDesc: 'Quelques moments qui reflètent notre univers et notre engagement.',
    testLabel: 'Avis Clients', testTitle: 'Ce que disent nos clients', testDesc: 'La satisfaction de nos clients est notre meilleure carte de visite.', testGoogle: 'sur Google', testBasé: 'Basé sur', testAvis: 'avis vérifiés',
    ctaTitle: 'Envie d\'en savoir plus ?', ctaDesc: 'Contactez-nous pour découvrir comment nous pouvons vous accompagner.',
    contactLabel: 'Nous contacter', contactTitle: 'Prenez Contact avec Nous', contactDesc: 'Envoyez-nous un message ou appelez-nous. Nous répondons rapidement.',
    formTitle: 'Envoyez votre demande', formDesc: 'Nous vous répondrons dans les plus brefs délais.', formName: 'Nom complet *', formPhone: 'Téléphone *', formEmail: 'Email', formMsg: 'Décrivez votre besoin *', formSubmit: 'Envoyer ma Demande →', formNote: 'Nous vous répondrons dans les meilleurs délais.',
    hoursTitle: 'Horaires d\'Ouverture', hoursLunVen: 'Lundi – Vendredi', hoursSam: 'Samedi', hoursDim: 'Dimanche',
    contactCall: 'Nous Appeler', footerNav: 'Navigation', footerContact: 'Contact', footerPrivacy: 'Politique de confidentialité',
    privacyTitle: 'Politique de Confidentialité',
    formPlaceholderName: 'Votre nom', formPlaceholderPhone: '06 XX XX XX XX', formPlaceholderEmail: 'votre@email.com', formPlaceholderMsg: 'Décrivez le problème ou les travaux souhaités...',
    whatsapp: 'WhatsApp',
  },
  en: {
    lang: 'en', hreflang: 'en',
    navAbout: 'About', navServices: 'Services', navWhy: 'Why Us', navAvis: 'Reviews', navContact: 'Contact',
    heroCall: 'Call Now', heroHours: 'Hours & Availability', heroNote: 'Quick response · No commitment',
    monLunVen: 'Mon – Fri', monSam: 'Saturday', monDim: 'Sunday', monDimUrg: 'Emergencies only',
    trustDefault: 'Certified Professional',
    svcLabel: 'What We Offer', svcTitle: 'Our Services', svcDesc: 'Services designed to meet your needs with care and expertise.', svcLink: 'Learn more',
    aboutLabel: 'About Us', aboutTitle: 'Our Business', aboutBadge: 'Years of Experience',
    whyLabel: 'Why Choose Us?', whySatisfaction: 'Satisfaction', whyExp: 'Years of Experience',
    statsAvis: 'Client Reviews', statsExp: 'Years Experience', statsNote: 'Google Rating', statsSat: 'Satisfaction',
    procLabel: 'How It Works', procTitle: 'A Tailored Approach', procDesc: 'From first contact to completion, we guide you every step of the way.',
    galleryLabel: 'Discover', galleryDesc: 'A glimpse into our world and what we stand for.',
    testLabel: 'Client Reviews', testTitle: 'What Our Clients Say', testDesc: 'Client satisfaction is our best recommendation.', testGoogle: 'on Google', testBasé: 'Based on', testAvis: 'verified reviews',
    ctaTitle: 'Want to Learn More?', ctaDesc: 'Contact us to discover how we can help you.',
    contactLabel: 'Get in Touch', contactTitle: 'Contact Us', contactDesc: 'Send us a message or give us a call. We respond quickly.',
    formTitle: 'Send Your Request', formDesc: 'We\'ll get back to you as soon as possible.', formName: 'Full Name *', formPhone: 'Phone *', formEmail: 'Email', formMsg: 'Describe your need *', formSubmit: 'Send Request →', formNote: 'We\'ll respond within 24 hours.',
    hoursTitle: 'Opening Hours', hoursLunVen: 'Monday – Friday', hoursSam: 'Saturday', hoursDim: 'Sunday',
    contactCall: 'Call Us', footerNav: 'Navigation', footerContact: 'Contact', footerPrivacy: 'Privacy Policy',
    privacyTitle: 'Privacy Policy',
    formPlaceholderName: 'Your name', formPlaceholderPhone: '+1 (555) 000-0000', formPlaceholderEmail: 'your@email.com', formPlaceholderMsg: 'Describe your issue or request...',
    whatsapp: 'WhatsApp',
  }
} as const;
